apiVersion: v1
name: fluent-bit-splunk
description: A Helm chart for Fluent-Bit. A Fast and lightweight log processor and forwarder or Linux, OSX and BSD family operating systems. It supports platform9 cluster types of BareOS, AWS, Azure, EKS. To send logs to splunk do update values.yaml during deploy with [Host](https://docs.fluentbit.io/manual/pipeline/outputs/splunk), [Splunk_Token](https://docs.splunk.com/Documentation/SplunkCloud/8.0.2006/Data/UsetheHTTPEventCollector?ref=hk) of your Splunk cloud. 
version: 0.15.14
appVersion: 1.7.8
keywords:
  - fluent-bit
  - splunk
icon: https://fluentbit.io/assets/img/logo1-default.png
home: https://github.com/platform9/helm-charts
sources:
  - https://github.com/platform9/helm-charts

